// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review_Site.Data;

#nullable disable

namespace Review_Site.Migrations
{
    [DbContext(typeof(ReviewSiteContext))]
    partial class ReviewSiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review_Site.Models.DestinationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationModelId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London, Edinborough, Dublin, Newport",
                            Country = "England, Scotland, Whales,Ireland",
                            Description = "The Colosseum in Rome, Italy, is a large amphitheater that hosted events like gladiatorial games.",
                            Name = "UK Tour",
                            Price = 10000m,
                            TourDuration = 10
                        },
                        new
                        {
                            Id = 2,
                            City = "Nara, Tokyo, Osaka, Kyoto",
                            Country = "Japan",
                            Description = "Nara Park, one of Nara's most famous destinations, is famous for being able to interact with deer that roam in the park. There are various spots in the vicinity, such as the Ukimido Pavilion and Mt. Wakakusa.",
                            Name = "Tour of Japan",
                            Price = 8000m,
                            TourDuration = 21
                        });
                });

            modelBuilder.Entity("Review_Site.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "It's okay",
                            DateTime = "20140112180244",
                            ImageURL = "https://res.taketours.com/images/640/Edinburgh%20Castle-Edinburgh-Scotland-UK.jpg",
                            ReviewerName = "Sergei",
                            StarRating = 5
                        },
                        new
                        {
                            Id = 2,
                            Content = "It's decent",
                            DateTime = "20140112180244",
                            ImageURL = "https://media.timeout.com/images/105240237/750/422/image.jpg",
                            ReviewerName = "Mat",
                            StarRating = 5
                        });
                });

            modelBuilder.Entity("Review_Site.Models.DestinationModel", b =>
                {
                    b.HasOne("Review_Site.Models.DestinationModel", null)
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationModelId");
                });

            modelBuilder.Entity("Review_Site.Models.DestinationModel", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
